## My First Notebook

Hello World
this is my first repository

In [1]:
import pandas as pd

Reading the list of

In [3]:
props = pd.read_csv("http://www.firstpythonnotebook.org/_static/committees.csv")

In [6]:
props.head(7)

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
0,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,382,1374469,YES ON PROPOSITION 51 - CALIFORNIANS FOR QUALI...,SUPPORT
1,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,383,1220380,COMMUNITY COLLEGE FACILITY COALITION ISSUES CO...,SUPPORT
2,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,384,1282321,TORLAKSON'S INVEST IN CALIFORNIA A BALLOT MEAS...,SUPPORT
3,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,385,1382843,CALIFORNIA TAXPAYERS AND EDUCATORS OPPOSED TO ...,OPPOSE
4,ocd-contest/85990193-9d6f-4600-b8e7-bf1317841d82,1362198,71,PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...,386,1362973,YES ON PROPOSITION 52 - A COALITION OF CALIFOR...,SUPPORT
5,ocd-contest/85990193-9d6f-4600-b8e7-bf1317841d82,1362198,71,PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...,387,1381488,CALIFORNIANS FOR HOSPITAL ACCOUNTABILITY AND Q...,OPPOSE
6,ocd-contest/85990193-9d6f-4600-b8e7-bf1317841d82,1362198,71,PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...,388,1373047,"SERVICE EMPLOYEES INTERNATIONAL UNION, UNITED ...",OPPOSE

In [7]:
props.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 8 columns):
ocd_prop_id               102 non-null object
calaccess_prop_id         102 non-null int64
ccdc_prop_id              102 non-null int64
prop_name                 102 non-null object
ccdc_committee_id         102 non-null int64
calaccess_committee_id    102 non-null int64
committee_name            102 non-null object
committee_position        102 non-null object
dtypes: int64(4), object(4)
memory usage: 6.4+ KB

Reading the list of contributions to ballot measures

In [8]:
contribs = pd.read_csv ("http://www.firstpythonnotebook.org/_static/contributions.csv")

In [10]:
contribs.head ()

,calaccess_committee_id,committee_name,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,BERGMAN,GRETCHEN,SPRING VALLEY,CA,91978,A NEW PATH,EXECUTIVE DIRECTOR,False,84.0
1,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,KAHLE,MYRNA,SAN DIEGO,CA,92109,NATIONAL SCHOOL DISTRICT,TEACHER,False,35.0
2,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-07-15,MCDEVITT,LEO,ESCONDIDO,CA,92025,LIFE IONIZERS,SEO/CONTENT MANAGER,False,198.0
3,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-08-10,WARREN-SAMARIPA,STEPHANIE,SAN DIEGO,CA,92116,STEPHANIE WARREN SAMARIPA,ENTREPRENEUR,False,-50.0
4,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-07-26,WARREN-SAMARIPA,STEPHANIE,SAN DIEGO,CA,92116,STEPHANIE WARREN SAMARIPA,ENTREPRENEUR,True,50.0

In [11]:
contribs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56379 entries, 0 to 56378
Data columns (total 13 columns):
calaccess_committee_id          56379 non-null int64
committee_name                  56379 non-null object
calaccess_filing_id             56379 non-null int64
date_received                   56379 non-null object
contributor_lastname            56375 non-null object
contributor_firstname           53411 non-null object
contributor_city                56369 non-null object
contributor_state               56363 non-null object
contributor_zip                 56366 non-null object
contributor_employer            48572 non-null object
contributor_occupation          53273 non-null object
contributor_is_self_employed    56379 non-null bool
amount                          56379 non-null float64
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 5.2+ MB

In [15]:
props.prop_name.value_counts().reset_index()

                                                index  prop_name
0   PROPOSITION 057 - CRIMINAL SENTENCES. JUVENILE...         13
1   PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...         12
2   PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...         11
3   PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...          9
4   PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...          8
5   PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...          7
6   PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...          7
7   PROPOSITION 059- SB 254 (CHAPTER 20, STATUTES ...          6
8   PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOT...          4
9   PROPOSITION 054 - LEGISLATURE. LEGISLATION AND...          4
10  PROPOSITION 058 - SB 1174 (CHAPTER 753, STATUT...          4
11  PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...          4
12  PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...          4
13  PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...          3
14  PROPOSITION 061- STATE PRESCRIPTION DRUG PURCH...          3
15  PROPOSITION 060- ADULT FILMS. CONDOMS. HEALTH ...          2
16  PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INIT...          1

In [16]:
contribs.contributor_occupation.value_counts().reset_index()

                              index  contributor_occupation
0              CORRECTIONAL OFFICER                   28617
1                           RETIRED                    3795
2                        UNEMPLOYED                    2630
3                      NOT EMPLOYED                    2500
4                          ATTORNEY                    1364
5                          ENGINEER                     537
6                         PROFESSOR                     393
7                         PHYSICIAN                     356
8                           TEACHER                     352
9                             OWNER                     305
10                           WRITER                     275
11                       CONSULTANT                     251
12                            SALES                     197
13                          MANAGER                     191
14                SOFTWARE ENGINEER                     172
15                         DIRECTOR                     164
16                        PRESIDENT                     160
17          CHIEF EXECUTIVE OFFICER                     122
18                     PSYCHOLOGIST                     113
19                        HOMEMAKER                     108
20                        SCIENTIST                     105
21                       CONTRACTOR                     102
22                           ARTIST                      97
23                 REGISTERED NURSE                      93
24                        EXECUTIVE                      92
25                     NOT-EMPLOYED                      87
26                      REAL ESTATE                      86
27                        ARCHITECT                      86
28                         DESIGNER                      82
29                        MARKETING                      81
...                             ...                     ...
2166                  TIMBER FARMER                       1
2167  ACTRESS/SCREENWRITER/PRODUCER                       1
2168         MEDICAL ADMINISTRATIVE                       1
2169                  AUTO DETAILER                       1
2170      VICE PRESIDENT OF REVENUE                       1
2171       VENTURE CAPITAL INVESTOR                       1
2172                        BARISTA                       1
2173                             DJ                       1
2174                      ECOMMERCE                       1
2175                          SOLAR                       1
2176                 MEDICAL CODING                       1
2177            POSTDOCTORAL FELLOW                       1
2178             COMPUTER PROGRAMER                       1
2179               PROFESSOR OF LAW                       1
2180                  WATER TESTING                       1
2181                           HVAC                       1
2182                    COPY EDITOR                       1
2183          DOCUMENTARY FILMMAKER                       1
2184                INSURANCE SALES                       1
2185                      BAR OWNER                       1
2186        ADMINISTRATIVE DIRECTOR                       1
2187                      PERFORMER                       1
2188                 PRIVATE EQUITY                       1
2189                        PAYROLL                       1
2190     INFRASTRUCTURE ENGINEERING                       1
2191     BUSINESS AFFAIRS EXECUTIVE                       1
2192          PHYSICIAN RADIOLOGIST                       1
2193              KNOWLEDGE MANAGER                       1
2194            FIREARMS INSTRUCTOR                       1
2195              TEACHER (RETIRED)                       1

[2196 rows x 2 columns]

In [18]:
props.prop_name.value_counts()

PROPOSITION 057 - CRIMINAL SENTENCES. JUVENILE CRIMINAL PROCEEDINGS AND SENTENCING. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.                           13
PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTHCARE, TOBACCO USE PREVENTION, RESEARCH, AND LAW ENFORCEMENT. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.    12
PROPOSITION 064- MARIJUANA LEGALIZATION. INITIATIVE STATUTE.                                                                                                   11
PROPOSITION 066- DEATH PENALTY. PROCEDURES. INITIATIVE STATUTE.                                                                                                 9
PROPOSITION 055 - TAX EXTENSION TO FUND EDUCATION AND HEALTHCARE. INITIATIVE CONSTITUTIONAL AMENDMENT.                                                          8
PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON SINGLE-USE PLASTIC BAGS.                                                                                         7
PROPOSITION 062- DEATH PENALTY. INITIATIVE STATUTE.                                                                                                             7
PROPOSITION 059- SB 254 (CHAPTER 20, STATUTES OF 2016), ALLEN. CAMPAIGN FINANCE: VOTER INSTRUCTION                                                              6
PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOTER APPROVAL. INITIATIVE CONSTITUTIONAL AMENDMENT.                                                                 4
PROPOSITION 054 - LEGISLATURE. LEGISLATION AND PROCEEDINGS. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.                                                    4
PROPOSITION 058 - SB 1174 (CHAPTER 753, STATUTES OF 2014), LARA. ENGLISH LANGUAGE EDUCATION                                                                     4
PROPOSITION 063- FIREARMS. AMMUNITION SALES. INTIATIVE STATUTE.                                                                                                 4
PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-12 SCHOOL AND COMMUNITY COLLEGE FACILITIES. INITIATIVE STATUTORY AMENDMENT.                                       4
PROPOSITION 052 - STATE FEES ON HOSPITALS. FEDERAL MEDI-CAL MATCHING FUNDS. INITIATIVE STATUTORY AND CONSTITUTIONAL AMENDMENT.                                  3
PROPOSITION 061- STATE PRESCRIPTION DRUG PURCHASES. PRICING STANDARDS. INITIATIVE STATUTE.                                                                      3
PROPOSITION 060- ADULT FILMS. CONDOMS. HEALTH REQUIREMENTS. INITIATIVE STATUTE.                                                                                 2
PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INITIATIVE STATUTE.                                                                                                   1
Name: prop_name, dtype: int64

In [20]:
prop = props[props.prop_name == "PROPOSITION 064- MARIJUANA LEGALIZATION. INITIATIVE STATUTE."]

In [21]:
prop.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
74,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT
75,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,457,1382525,NEW APPROACH PAC (MPO),SUPPORT
76,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,458,1376077,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",SUPPORT
77,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,459,1382568,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",OPPOSE
78,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,460,1371855,"MARIJUANA POLICY PROJECT OF CALIFORNIA, YES ON 64",SUPPORT

In [22]:
prop.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11 entries, 74 to 84
Data columns (total 8 columns):
ocd_prop_id               11 non-null object
calaccess_prop_id         11 non-null int64
ccdc_prop_id              11 non-null int64
prop_name                 11 non-null object
ccdc_committee_id         11 non-null int64
calaccess_committee_id    11 non-null int64
committee_name            11 non-null object
committee_position        11 non-null object
dtypes: int64(4), object(4)
memory usage: 792.0+ bytes

In [23]:
contribs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56379 entries, 0 to 56378
Data columns (total 13 columns):
calaccess_committee_id          56379 non-null int64
committee_name                  56379 non-null object
calaccess_filing_id             56379 non-null int64
date_received                   56379 non-null object
contributor_lastname            56375 non-null object
contributor_firstname           53411 non-null object
contributor_city                56369 non-null object
contributor_state               56363 non-null object
contributor_zip                 56366 non-null object
contributor_employer            48572 non-null object
contributor_occupation          53273 non-null object
contributor_is_self_employed    56379 non-null bool
amount                          56379 non-null float64
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 5.2+ MB

In [26]:
merged = pd.merge(prop, contribs, on="calaccess_committee_id")

In [27]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 860 entries, 0 to 859
Data columns (total 20 columns):
ocd_prop_id                     860 non-null object
calaccess_prop_id               860 non-null int64
ccdc_prop_id                    860 non-null int64
prop_name                       860 non-null object
ccdc_committee_id               860 non-null int64
calaccess_committee_id          860 non-null int64
committee_name_x                860 non-null object
committee_position              860 non-null object
committee_name_y                860 non-null object
calaccess_filing_id             860 non-null int64
date_received                   860 non-null object
contributor_lastname            860 non-null object
contributor_firstname           750 non-null object
contributor_city                860 non-null object
contributor_state               860 non-null object
contributor_zip                 860 non-null object
contributor_employer            657 non-null object
contributor_occupation          742 non-null object
contributor_is_self_employed    860 non-null bool
amount                          860 non-null float64
dtypes: bool(1), float64(1), int64(5), object(13)
memory usage: 135.2+ KB

In [28]:
merged.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-02-04,BRADEN QUIGLEY,LAURA,SACRAMENTO,CA,95825,LBQ STRATEGIES,CONSULTANT,False,100.0
1,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-01-05,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",NaN,IRVINE,CA,92618,NaN,NaN,False,250000.0
2,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-01-29,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",NaN,IRVINE,CA,92618,NaN,NaN,False,250000.0
3,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-03-28,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",NaN,IRVINE,CA,92618,NaN,NaN,False,250000.0
4,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-01-05,DRUG POLICY ACTION,NaN,NEW YORK,NY,10001,NaN,NaN,False,250000.0

In [29]:
merged.value_counts().reset_index

AttributeError: 'DataFrame' object has no attribute 'value_counts'

In [30]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 860 entries, 0 to 859
Data columns (total 20 columns):
ocd_prop_id                     860 non-null object
calaccess_prop_id               860 non-null int64
ccdc_prop_id                    860 non-null int64
prop_name                       860 non-null object
ccdc_committee_id               860 non-null int64
calaccess_committee_id          860 non-null int64
committee_name_x                860 non-null object
committee_position              860 non-null object
committee_name_y                860 non-null object
calaccess_filing_id             860 non-null int64
date_received                   860 non-null object
contributor_lastname            860 non-null object
contributor_firstname           750 non-null object
contributor_city                860 non-null object
contributor_state               860 non-null object
contributor_zip                 860 non-null object
contributor_employer            657 non-null object
contributor_occupation          742 non-null object
contributor_is_self_employed    860 non-null bool
amount                          860 non-null float64
dtypes: bool(1), float64(1), int64(5), object(13)
memory usage: 135.2+ KB

In [31]:
merged.amount.sum()

35177017.640000001

In [32]:
merged.committee_position.value_counts()

SUPPORT    762
OPPOSE      98
Name: committee_position, dtype: int64

In [33]:
support = merged[merged.committee_position == "SUPPORT"]

In [34]:
oppose = merged[merged.committee_position == "OPPOSE"]

support.amount.sum()

In [36]:
oppose.amount.sum()

2501211.6400000001

In [37]:
support.amount.sum() / merged.amount.sum()

0.92889642704798669

In [43]:
oppose.sort_values("amount", ascending=False).head(10)

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
839,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,463,1387789,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",OPPOSE,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",2083142,2016-07-20,SCHAUER,JULIE,OAKS,PA,19456,NaN,RETIRED,False,1000000.0
312,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,459,1382568,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",OPPOSE,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",2098048,2016-09-27,"SAM ACTION, INC.",NaN,ALEXANDRIA,VA,22314,NaN,NaN,False,400000.0
310,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,459,1382568,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",OPPOSE,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",2083071,2016-09-15,"SAM ACTION, INC.",NaN,ALEXANDRIA,VA,22314,NaN,NaN,False,225000.0
308,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,459,1382568,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",OPPOSE,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",2083071,2016-09-12,"SAM ACTION, INC.",NaN,ALEXANDRIA,VA,22314,NaN,NaN,False,200000.0
840,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,463,1387789,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",OPPOSE,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",2083142,2016-07-25,SCHAUER,JULIE,OAKS,CA,19456,NaN,RETIRED,False,150000.0
837,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,463,1387789,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",OPPOSE,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",2064155,2016-06-08,SCHAUER,JULIE,OAKS,PA,19456,NaN,RETIRED,False,120000.0
838,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,463,1387789,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",OPPOSE,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",2064155,2016-06-13,SCHAUER,JULIE,OAKS,PA,19456,NaN,RETIRED,False,45000.0
287,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,459,1382568,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",OPPOSE,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",2064127,2016-06-13,"SAM ACTION, INC.",NaN,ALEXANDRIA,VA,22314,NaN,NaN,False,36000.0
836,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,463,1387789,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",OPPOSE,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",2064155,2016-05-20,SCHAUER,JULIE,OAKS,PA,19456,NaN,RETIRED,False,35000.0
306,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,459,1382568,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",OPPOSE,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",2083071,2016-09-07,"CALIFORNIANS FOR JOBS, ASSEMBLYMEMBER JIM COOP...",NaN,SACRAMENTO,CA,95815,NaN,NaN,False,25000.0

In [50]:
merged.groupby("committee_name_x").amount.sum().reset_index().sort_values("amount", ascending=False)

                                     committee_name_x       amount
10  YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...  15734047.00
4        FUND FOR POLICY REFORM (NONPROFIT 501(C)(4))   6140000.00
3   DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...   4470000.00
7                              NEW APPROACH PAC (MPO)   3865000.00
9   SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...   1364000.00
8   PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...   1130930.00
1   CALIFORNIANS FOR RESPONSIBLE MARIJUANA REFORM,...    860470.00
2   CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...    850000.00
5   MARIJUANA POLICY PROJECT OF CALIFORNIA, YES ON 64    739200.00
0          ADULT USE CAMPAIGN FOR PROPOSITION 64; THE     17089.00
6                         MOMS STRONG AGAINST PROP 64      6281.64

In [51]:
merged.groupby(["contributor_firstname","contributor_lastname"]).amount.sum().reset_index().sort_values("amount", ascending=False)

    contributor_firstname            contributor_lastname     amount
483                  SEAN  PARKER AND AFFILIATED ENTITIES  7250000.0
482                  SEAN                          PARKER  1500000.0
281                 JULIE                         SCHAUER  1364000.0
108                DANIEL                           LEWIS  1250000.0
194                 HENRY                   VAN AMERINGEN  1000000.0
405              NICHOLAS                        PRITZKER   900000.0
421                 PETER                           THIEL   300000.0
456                 ROGER                         JENKINS    75000.0
23                 ANGELA                          HOWARD    65000.0
322              LAWRENCE                            HESS    30000.0
221                 JASON                            POST    10000.0
460              ROGER B.                         MCNAMEE    10000.0
548           ZACHARY PYM                        WILLIAMS    10000.0
239                JEREMY                         ZACHARY     7500.0
440                ROBERT                           ADAMS     6500.0
320                LAURIE                        BENENSON     5000.0
63                CAMILLA                           FIELD     5000.0
375               MICHAEL                            DEAN     5000.0
361            MARY QUINN                         DELANEY     5000.0
488             SHARON K.                        CHRISTIE     5000.0
515                 TERRY                          TURNER     3664.0
301              KHURSHID                           KHOJA     3300.0
277                  JULI                        CROCKETT     3000.0
149                  DOUG                        LANPHERE     2920.0
76                CHARLES                           ROVEN     2500.0
158                 EMILY                          PAXHIA     2500.0
414               PATRICK                       MCMANAMON     2500.0
507                STEVEN                          PERSKY     2500.0
382               MICHAEL                       STEINMETZ     2500.0
377               MICHAEL                           KLEIN     2500.0
..                    ...                             ...        ...
75                CHARLES                            LOVE      100.0
191              GRETCHEN                         BERGMAN       84.0
387              MICHELLE                           WOLFF       84.0
385              MICHELLE                          SEXTON       84.0
189                  GREG                           SMITH       75.0
389                  MIKE                         BARNETT       50.0
534                 WENDY                          COLTON       50.0
168                 ETHAN                         BROOKES       50.0
85           CHRISTINE A.                          PORTER       50.0
459                 ROGER                           TOWER       50.0
492                  SKIP                          ROACHE       50.0
335              LJUBOMIR                       BUTUROVIC       50.0
418                 PETER                          KIRSCH       50.0
326               LEONARD                        KAUFMANN       50.0
104                  DANA                          HIRSCH       50.0
105                DANIEL                          DODSON       50.0
125                 DAVID                          MURRAY       50.0
272                  JOSH                       KLEYMEYER       42.0
51                  BRIAN                        MITCHELL       35.0
533                 WAYNE                         SCHERER       30.0
448                ROBERT                         LOCKART       25.0
185                GEORGE                          OKEEFE       25.0
510               SUE ANN                           LORIG       25.0
355                  MARK                        SLABAUGH       25.0
540               WILLIAM                        SANTSCHI       25.0
430                  RICH                        GOLDBERG       25.0
358               MARSTON                         MEDLOCK        0.0
497             STEPHANIE                 WARREN-SAMARIPA        0.0
16             AMIRGHASEM                 SAMIMI-ARDESTAN        0.0
136                 DAVID                            WOOD        0.0

[549 rows x 3 columns]

In [52]:
merged.groupby(["contributor_firstname","contributor_lastname","committee_position"]).amount.sum().reset_index().sort_values("amount", ascending=False)

,contributor_firstname,contributor_lastname,committee_position,amount
483,SEAN,PARKER AND AFFILIATED ENTITIES,SUPPORT,7250000.0
482,SEAN,PARKER,SUPPORT,1500000.0
281,JULIE,SCHAUER,OPPOSE,1364000.0
108,DANIEL,LEWIS,SUPPORT,1250000.0
194,HENRY,VAN AMERINGEN,SUPPORT,1000000.0
405,NICHOLAS,PRITZKER,SUPPORT,900000.0
421,PETER,THIEL,SUPPORT,300000.0
456,ROGER,JENKINS,SUPPORT,75000.0
23,ANGELA,HOWARD,SUPPORT,65000.0
322,LAWRENCE,HESS,SUPPORT,30000.0
221,JASON,POST,SUPPORT,10000.0
460,ROGER B.,MCNAMEE,SUPPORT,10000.0
548,ZACHARY PYM,WILLIAMS,SUPPORT,10000.0
239,JEREMY,ZACHARY,SUPPORT,7500.0
440,ROBERT,ADAMS,OPPOSE,6500.0
320,LAURIE,BENENSON,SUPPORT,5000.0
63,CAMILLA,FIELD,SUPPORT,5000.0
375,MICHAEL,DEAN,OPPOSE,5000.0
361,MARY QUINN,DELANEY,SUPPORT,5000.0
488,SHARON K.,CHRISTIE,SUPPORT,5000.0
515,TERRY,TURNER,SUPPORT,3664.0
301,KHURSHID,KHOJA,SUPPORT,3300.0
277,JULI,CROCKETT,SUPPORT,3000.0
149,DOUG,LANPHERE,SUPPORT,2920.0
76,CHARLES,ROVEN,SUPPORT,2500.0
158,EMILY,PAXHIA,SUPPORT,2500.0
414,PATRICK,MCMANAMON,SUPPORT,2500.0
507,STEVEN,PERSKY,SUPPORT,2500.0
382,MICHAEL,STEINMETZ,SUPPORT,2500.0
377,MICHAEL,KLEIN,SUPPORT,2500.0
...,...,...,...,...
75,CHARLES,LOVE,SUPPORT,100.0
191,GRETCHEN,BERGMAN,SUPPORT,84.0
387,MICHELLE,WOLFF,SUPPORT,84.0
385,MICHELLE,SEXTON,SUPPORT,84.0
189,GREG,SMITH,SUPPORT,75.0
389,MIKE,BARNETT,SUPPORT,50.0
534,WENDY,COLTON,SUPPORT,50.0
168,ETHAN,BROOKES,SUPPORT,50.0
85,CHRISTINE A.,PORTER,SUPPORT,50.0
459,ROGER,TOWER,SUPPORT,50.0
492,SKIP,ROACHE,SUPPORT,50.0
335,LJUBOMIR,BUTUROVIC,SUPPORT,50.0
418,PETER,KIRSCH,SUPPORT,50.0
326,LEONARD,KAUFMANN,SUPPORT,50.0
104,DANA,HIRSCH,SUPPORT,50.0
105,DANIEL,DODSON,SUPPORT,50.0
125,DAVID,MURRAY,SUPPORT,50.0
272,JOSH,KLEYMEYER,SUPPORT,42.0
51,BRIAN,MITCHELL,SUPPORT,35.0
533,WAYNE,SCHERER,SUPPORT,30.0
448,ROBERT,LOCKART,SUPPORT,25.0
185,GEORGE,OKEEFE,SUPPORT,25.0
510,SUE ANN,LORIG,SUPPORT,25.0
355,MARK,SLABAUGH,SUPPORT,25.0
540,WILLIAM,SANTSCHI,SUPPORT,25.0
430,RICH,GOLDBERG,SUPPORT,25.0
358,MARSTON,MEDLOCK,SUPPORT,0.0
497,STEPHANIE,WARREN-SAMARIPA,SUPPORT,0.0
16,AMIRGHASEM,SAMIMI-ARDESTAN,SUPPORT,0.0
136,DAVID,WOOD,SUPPORT,0.0